version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: pasifix-backend
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        ports:
            - "9000:9000"
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:4pseE1/iEPRU+L1Xl3vMLjLkLRNgYLPUS5ZJ0oUzJPA=
            - APP_URL=http://localhost:9000
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=pasifix
            - DB_USERNAME=root
            - DB_PASSWORD=password
            - CACHE_DRIVER=file
            - SESSION_DRIVER=file
            - QUEUE_CONNECTION=sync
            - CLOUDINARY_CLOUD_NAME=dm3icigfr
            - CLOUDINARY_API_KEY=368671751925851
            - CLOUDINARY_API_SECRET=vkeX0XBXwodlqFPWbBUNUQQf80E
        depends_on:
            - db
        networks:
            - pasifix-network

    db:
        image: mysql:8.0
        container_name: pasifix-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: pasifix
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: pasifix
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - pasifix-network

volumes:
    dbdata:
        driver: local

networks:
    pasifix-network:
        driver: bridge
